FROM node:20-alpine

WORKDIR /app

COPY frontend/package.json frontend/vite.config.js frontend/tailwind.config.js frontend/postcss.config.js /app/
COPY frontend/index.html /app/index.html
COPY frontend/src /app/src

RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

